name:                AoC2018
version:             0.1.0.0
synopsis:            Advent of Code 2018
homepage:            https://github.com/CarstenKoenig/AoC2018#readme
license:             BSD3
author:              Carsten König
maintainer:          Carsten@gettingsharper.de
category:            Fun
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - ansi-terminal
  - array
  - astar
  - containers
  - hashable
  - mtl
  - parsec 
  - text
  - time
  - unordered-containers

default-extensions:
  - OverloadedStrings
  - BangPatterns

executables:
  AoC2018:
    source-dirs:      src
    main:             Main.hs
    ghc-options:
      -O2
      -threaded
      -Wall
